batch_size: 30
epochs: 1
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  input_type: image
  model: lora_vit
language:
  input_type: sequence
  model: lora_bert

no_image:
  input_type: dict
  model: no_lora


bioscan_bert_checkpoint: ${project_root_path}/ckpt/BarcodeBERT/5_mer/model_41.pth
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/lora_vit_lora_bert_ssl_batch_size_400/best.pth
model_output_dir: ${project_root_path}/ckpt/bioscan_clip
model_output_name: lora_vit_lora_bert_ssl_batch_size_400
evaluation_period: 1
output_dim: 768
port: 12317