debug_flag: true

defaults:
  - _self_
  - model_config: mlp_ssl
project_root_path: ${hydra:runtime.cwd}
data_dir: ${project_root_path}/data
activate_wandb: false
save_inference : true
load_inference: false
bioscan_data:
  dir: ${data_dir}/BioScan_1M
  path_to_hdf5_data: ${bioscan_data.dir}/split_data/BioScan_data_in_splits.hdf5
  path_to_tsv_data: ${bioscan_data.dir}/BioScan_Insect_Dataset_metadata_2.tsv
  path_to_small_species_list_json: ${bioscan_data.dir}/small_species_list.json
insect_data:
  dir: ${data_dir}/INSECT
  path_to_att_splits_mat: ${insect_data.dir}/att_splits.mat
  path_to_res_101_mat: ${insect_data.dir}/res101.mat
  path_to_feature_hdf5: ${insect_data.dir}/extracted_features/clip_barcodebert_extracted_features.hdf5
  path_to_image_hdf5: ${insect_data.dir}/INSECT_images.hdf5
  path_to_meta_csv: ${insect_data.dir}/INSECT_metadata.csv
  image_dir: ${insect_data.dir}/images
  species_to_other: ${insect_data.dir}/specie_to_other_labels.json
save_ckpt: true
bioscan_bert_checkpoint: ${project_root_path}/ckpt/BarcodeBERT/5_mer/model_41.pth
current_version: 0.1
model_output_dir: ${project_root_path}/ckpt/bioscan_clip

inference_and_eval_setting:
  plot_embeddings: true
  retrieve_images: true
  query_feature_type: image
  key_feature_type: image
  k_list: [1, 3, 5]
  levels: ['order', 'family', 'genus', 'species']
  embeddings_filters:
    order: Diptera
    family: Sciaridae
    genus: Corynoptera
  put_all_key_together: false
  eval_on: val

visualization:
  output_dir: ${project_root_path}/visualizations
  key_feature_type: image
  k: 10

general_fine_tune_setting:
  save_ckpt: true
  epoch: 150
  batch_size: 200


