batch_size: 100
epochs: 80
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP_fine_tune_on_INSECT_dataset
using_train_seen_for_pre_train: true
dataset: INSECT

image:
  input_type: image
  model: lora_vit
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_bert

model_output_name: image_dna_text_4gpu_fine_tune_on_INSECT_dataset
evaluation_period: 1


pretrained_ckpt_path: ${project_root_path}/ckpt/bioscan_clip/final_experiments/image_dna_text_4gpu_epoch50/best.pth
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/trained_with_INSECT/image_dna_text_4gpu_epoch50/best.pth

use_ckpt_fine_tuned_on_INSECT_dataset: true

output_dim: 768
port: 29531

disable_lora: true
lr_scheduler: one_cycle
lr_config:
  lr: 1e-6
  max_lr: 3e-6

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: false
amp: true

random_seed: false

eval_skip_epoch: 70

default_seed: 42

fine_tuning_set:
  batch_size: 150
  epochs: 15
  fine_tune_model_output_dir: ${model_output_dir}/${model_config.model_output_name}/supervise_fine_tune_ckpt