batch_size: 300
epochs: 1
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-small_experiments
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  input_type: image
  model: lora_vit
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_bert

model_output_name: lora_with_small_learning_rate
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/full_fine_tuning_one_cycle_lr_sche_with_all_gather/image_dna_text.pth
output_dim: 768
port: 29531

lr_scheduler: cosine
lr_config:
  lr: 0.00005
  min_lr: 0.000001

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: true
amp: true
